// for info check http://gmsh.info/doc/texinfo/gmsh.html

h=0.1;  // mesh density parameter around Point(). Each point can have its parameter h1, h2...

// square domain
Point(1) = {0.0000,0.0000,0,h}; // define the four corners of the square domain
Point(2) = {20.0000,0.0000,0,h};
Point(3) = {20.0000,10.0000,0,h};
Point(4) = {0.0000,10.0000,0,h};

Line(1) = {1,2}; // define the four sides of the square domain
Line(2) = {2,3};
Line(3) = {3,4};
Line(4) = {4,1};
Line Loop(1) = {1,2,3,4}; // define region: boundary of square domain


// circular tubes

// tube #1
x=5; // coordinate center
y=3.33;
r=1; // radius

// boundary of circular tube generated by means of four arches defined via Circle arc
// each Circle arc needs center and two points in this sequence: start point, center, end point of the arc
Point(5) = {x   ,y   ,0,h};
Point(6) = {x+r ,y   ,0,h};
Point(7) = {x   ,y+r ,0,h};
Point(8) = {x-r ,y   ,0,h};
Point(9) = {x   ,y-r ,0,h};

Circle(5) = {6,5,7};
Circle(6) = {7,5,8};
Circle(7) = {8,5,9};
Circle(8) = {9,5,6};
// define region: boundary of tube
// the line loop instruction generates an oriented line loop. This must be a closed loop, and the elementary lines on the right hand side should be ordered and oriented (using negative identification numbers to specify reverse orientation)
Line Loop(2) = {5,6,7,8};

// tube #2
x=10; // coordinate center
y=3.33;
r=1; // radius

// boundary of tube generated by means of four arches defined via Circle arc
// each Circle arc needs center and two points in this sequence: start point, center, end point of the arc
Point(10) = {x   ,y   ,0,h};
Point(11) = {x+r ,y   ,0,h};
Point(12) = {x   ,y+r ,0,h};
Point(13) = {x-r ,y   ,0,h};
Point(14) = {x   ,y-r ,0,h};

Circle(9) = {11,10,12};
Circle(10) = {12,10,13};
Circle(11) = {13,10,14};
Circle(12) = {14,10,11};
// define region: boundary of tube
// the line loop instruction generates an oriented line loop. This must be a closed loop, and the elementary lines on the right hand side should be ordered and oriented (using negative identification numbers to specify reverse orientation)
Line Loop(3) = {9,10,11,12};

// tube #3
x=15; // coordinate center
y=3.33;
r=1; // radius

// boundary of tube generated by means of four arches defined via Circle arc
// each Circle arc needs center and two points in this sequence: start point, center, end point of the arc
Point(15) = {x   ,y   ,0,h};
Point(16) = {x+r ,y   ,0,h};
Point(17) = {x   ,y+r ,0,h};
Point(18) = {x-r ,y   ,0,h};
Point(19) = {x   ,y-r ,0,h};

Circle(13) = {16,15,17};
Circle(14) = {17,15,18};
Circle(15) = {18,15,19};
Circle(16) = {19,15,16};
// define region: boundary of tube
// the line loop instruction generates an oriented line loop. This must be a closed loop, and the elementary lines on the right hand side should be ordered and oriented (using negative identification numbers to specify reverse orientation)
Line Loop(4) = {13,14,15,16};

// tube #4
x=15; // coordinate center
y=6.66;
r=1; // radius

// boundary of tube generated by means of four arches defined via Circle arc
// each Circle arc needs center and two points in this sequence: start point, center, end point of the arc
Point(20) = {x   ,y   ,0,h};
Point(21) = {x+r ,y   ,0,h};
Point(22) = {x   ,y+r ,0,h};
Point(23) = {x-r ,y   ,0,h};
Point(24) = {x   ,y-r ,0,h};

Circle(17) = {21,20,22};
Circle(18) = {22,20,23};
Circle(19) = {23,20,24};
Circle(20) = {24,20,21};
// define region: boundary of tube
// the line loop instruction generates an oriented line loop. This must be a closed loop, and the elementary lines on the right hand side should be ordered and oriented (using negative identification numbers to specify reverse orientation)
Line Loop(5) = {17,18,19,20};

// tube #5
x=10; // coordinate center
y=6.66;
r=1; // radius

// boundary of tube generated by means of four arches defined via Circle arc
// each Circle arc needs center and two points in this sequence: start point, center, end point of the arc
Point(25) = {x   ,y   ,0,h};
Point(26) = {x+r ,y   ,0,h};
Point(27) = {x   ,y+r ,0,h};
Point(28) = {x-r ,y   ,0,h};
Point(29) = {x   ,y-r ,0,h};

Circle(21) = {26,25,27};
Circle(22) = {27,25,28};
Circle(23) = {28,25,29};
Circle(24) = {29,25,26};
// define region: boundary of tube
// the line loop instruction generates an oriented line loop. This must be a closed loop, and the elementary lines on the right hand side should be ordered and oriented (using negative identification numbers to specify reverse orientation)
Line Loop(6) = {21,22,23,24};

// tube #6
x=5; // coordinate center
y=6.66;
r=1; // radius

// boundary of tube generated by means of four arches defined via Circle arc
// each Circle arc needs center and two points in this sequence: start point, center, end point of the arc
Point(30) = {x   ,y   ,0,h};
Point(31) = {x+r ,y   ,0,h};
Point(32) = {x   ,y+r ,0,h};
Point(33) = {x-r ,y   ,0,h};
Point(34) = {x   ,y-r ,0,h};

Circle(25) = {31,30,32};
Circle(26) = {32,30,33};
Circle(27) = {33,30,34};
Circle(28) = {34,30,31};
// define region: boundary of tube
// the line loop instruction generates an oriented line loop. This must be a closed loop, and the elementary lines on the right hand side should be ordered and oriented (using negative identification numbers to specify reverse orientation)
Line Loop(7) = {25,26,27,28};

// Creates a plane surface. The expression inside the parentheses is the plane surface’s tag; the expression-list on the right hand side should contain the tags of all the curve loops defining the surface. The first curve loop defines the exterior boundary of the surface; all other curve loops define holes in the surface.


Plane Surface(1) = {2}; // tube #1
Plane Surface(2) = {3}; // tube #2
Plane Surface(3) = {4}; // tube #3
Plane Surface(4) = {5}; // tube #4
Plane Surface(5) = {6}; // tube #5
Plane Surface(6) = {7}; // tube #6

Plane Surface(7) = {1, 2, 3, 4, 5, 6, 7}; // matrix: domain minus tubes


// The text below is copied from an online example (and slightly adapted to the composite example)
// At this level, Gmsh knows everything to display the rectangular domain with inclusion and
// to mesh it. If we want to group elementary geometrical entities into meaningful groups, e.g. to define some
// mathematical ("domain", "boundary"), functional ("left wing", "fuselage") or material ("steel", "carbon") properties.
//
// Such groups are called "Physical Groups" in GMSH. By default, if physical
// groups are defined, GMSH will export in output files only those elements that
// belong to at least one physical group. (To force GMSH to save all elements,
// whether they belong to physical groups or not, set "Mesh.SaveAll=1;", or
// specify "-save_all" on the command line.)
//
// Here we define a physical curve that groups the left, bottom and right lines
// in a single group (with prescribed tag 5); and a physical surface with name
// "My surface" (with an automatic tag) containg the geometrical surface 1:

//Physical Curve(5) = {1, 2, 4} ;
//Physical Surface("My surface") = {1} ;

Physical Surface("matrix") = {7};
Physical Surface("tube_cold") = {1,3,5}; //add all cold tubes to this list if they have the same properties
Physical Surface("tube_hot") = {2,4,6}; //add all hot tubes to this list if they have the same properties
Physical Point("bottom left corner") = {1}; //this is the label given to Point(1) = {0.0000,0.0000,0,h}
Physical Curve("cold_surface") = {5,6,7,8,13,14,15,16,21,22,23,24};
Physical Curve("hot_surface") = {9,10,11,12,17,18,19,20,25,26,27,28};

